### ISSUE TITLE
Add Contributing folder

### ISSUE THREAD

**Issue by Akshith-S** [cyai/YT2Brief#7]
It would be really helpful for newbies in Open Source to have a separate folder for how to contribute. It includes detailed step by step guide to use Git. It must start from how to fork the repository to submit a pull request and finally push the commit to the main branch. Also, it would be useful if screenshots of every git command used is tagged in the side to have a better visual understanding of the procedure.

**Comment by cyai** [comment]
Are you willing to do it?

**Comment by Akshith-S** [comment]
Hello,
I'm willing to. But it could take some time since I've my exams coming shortly. Anyways, I'll try to complete the task as soon as possible.

**Comment by virajsazzala** [comment]
@Akshith-S Is that really necessary? I believe a `contributing.md` file would do the job. A folder to learn how to contribute would be too much and redundant.

@cyai thoughts?

**Comment by yuvicc** [comment]
Can I do this?

**Comment by cyai** [comment]
> @Akshith-S Is that really necessary? I believe a `contributing.md` file would do the job. A folder to learn how to contribute would be too much and redundant.
> 
> @cyai thoughts?

yes, I think the same too! Just a contributing.md file would be more then enough.
